Repository wanted-preonboarding-backend-teamV/SNS-Integration-Service, pull requests merged in 2023-10, with the labels that each got.

#2 feat #1 - 엔티티 구현
  src/main/java/com/wanted/teamV/entity/Member.java
  src/main/java/com/wanted/teamV/entity/Post.java
  src/main/java/com/wanted/teamV/entity/PostHashtag.java
  src/main/java/com/wanted/teamV/entity/PostHistory.java
  src/main/java/com/wanted/teamV/type/HistoryType.java
  src/main/java/com/wanted/teamV/type/MemberStatus.java
  src/main/java/com/wanted/teamV/type/SnsType.java
Labels: feature

#3 Feat/#1
  src/main/java/com/wanted/teamV/entity/Post.java
Labels: feature

#5 feat #4 Exception 구현
  src/main/java/com/wanted/teamV/exception/CustomException.java
  src/main/java/com/wanted/teamV/exception/ErrorCode.java
  src/main/java/com/wanted/teamV/exception/ErrorResponse.java
  src/main/java/com/wanted/teamV/exception/GlobalExceptionHandler.java
Labels: feature

#7 feat #6 Repository 구현
  src/main/java/com/wanted/teamV/repository/MemberRepository.java
  src/main/java/com/wanted/teamV/repository/PostHashtagRepository.java
  src/main/java/com/wanted/teamV/repository/PostHistoryRepository.java
  src/main/java/com/wanted/teamV/repository/PostRepository.java
Labels: feature

#9 fix #1 Entity Join 수정
  src/main/java/com/wanted/teamV/entity/PostHashtag.java
  src/main/java/com/wanted/teamV/entity/PostHistory.java
Labels: bug

#13 fix #1 - 엔티티 설정 오타 수정
  src/main/java/com/wanted/teamV/entity/PostHashtag.java
Labels: bug

#16 fix #4 - 예외 처리 클래스 수정
  src/main/java/com/wanted/teamV/exception/CustomException.java
  src/main/java/com/wanted/teamV/exception/GlobalExceptionHandler.java
Labels: bug

#19 feat #15 - 게시물 생성 기능 구현
  src/main/java/com/wanted/teamV/config/JpaAuditingConfig.java
  src/main/java/com/wanted/teamV/controller/PostController.java
  src/main/java/com/wanted/teamV/dto/req/PostCreateReqDto.java
  src/main/java/com/wanted/teamV/entity/Post.java
  src/main/java/com/wanted/teamV/repository/PostHashtagRepository.java
  src/main/java/com/wanted/teamV/service/PostService.java
  src/main/java/com/wanted/teamV/service/impl/PostServiceImpl.java
  src/main/java/com/wanted/teamV/type/SnsType.java
  src/test/java/com/wanted/teamV/controller/PostControllerTest.java
  src/test/java/com/wanted/teamV/service/PostServiceImplTest.java
Labels: feature

#21 Feat/#10 - 통계 조회 기능 구현
  build.gradle
  src/main/java/com/wanted/teamV/config/QueryDslConfig.java
  src/main/java/com/wanted/teamV/config/WebConfig.java
  src/main/java/com/wanted/teamV/controller/StatisticsController.java
  src/main/java/com/wanted/teamV/dto/res/StatisticsResDto.java
  src/main/java/com/wanted/teamV/entity/PostHistory.java
  src/main/java/com/wanted/teamV/exception/ErrorCode.java
  src/main/java/com/wanted/teamV/repository/PostHashtagRepository.java
  src/main/java/com/wanted/teamV/repository/PostHistoryRepository.java
  src/main/java/com/wanted/teamV/repository/PostHistoryRepositoryCustom.java
  src/main/java/com/wanted/teamV/repository/PostRepository.java
  src/main/java/com/wanted/teamV/repository/PostRepositoryCustom.java
  src/main/java/com/wanted/teamV/repository/impl/PostHistoryRepositoryImpl.java
  src/main/java/com/wanted/teamV/repository/impl/PostRepositoryImpl.java
  src/main/java/com/wanted/teamV/service/StatisticsService.java
  src/main/java/com/wanted/teamV/service/impl/StatisticsServiceImpl.java
  src/main/java/com/wanted/teamV/type/HistoryType.java
  src/main/java/com/wanted/teamV/type/StatisticsSortType.java
  src/main/java/com/wanted/teamV/type/StatisticsTimeType.java
  src/main/java/com/wanted/teamV/type/StatisticsValueType.java
  src/main/java/com/wanted/teamV/type/converter/StringToStatisticsSortTypeConverter.java
  src/main/java/com/wanted/teamV/type/converter/StringToStatisticsTimeTypeConverter.java
  src/main/java/com/wanted/teamV/type/converter/StringToStatisticsValueTypeConverter.java
  src/test/java/com/wanted/teamV/controller/StatisticsControllerTest.java
  src/test/java/com/wanted/teamV/service/impl/StatisticsServiceImplTest.java
Labels: feature, test

#29 feat #15 - 게시물 생성시 사용자 인증기능 추가
  src/main/java/com/wanted/teamV/config/WebConfig.java
  src/main/java/com/wanted/teamV/controller/PostController.java
  src/main/java/com/wanted/teamV/dto/req/PostCreateReqDto.java
  src/main/java/com/wanted/teamV/exception/ErrorCode.java
  src/test/java/com/wanted/teamV/controller/PostControllerTest.java
Labels: feature, test

#35 feat #22 - 게시물 목록 조회 API 구현
  src/main/java/com/wanted/teamV/config/WebConfig.java
  src/main/java/com/wanted/teamV/controller/PostController.java
  src/main/java/com/wanted/teamV/dto/res/ListResDto.java
  src/main/java/com/wanted/teamV/dto/res/PostResDto.java
  src/main/java/com/wanted/teamV/exception/CustomException.java
  src/main/java/com/wanted/teamV/exception/ErrorCode.java
  src/main/java/com/wanted/teamV/repository/PostHashtagRepository.java
  src/main/java/com/wanted/teamV/repository/PostHashtagRepositoryCustom.java
  src/main/java/com/wanted/teamV/repository/PostRepositoryCustom.java
  src/main/java/com/wanted/teamV/repository/impl/PostHashtagRepositoryImpl.java
  src/main/java/com/wanted/teamV/repository/impl/PostRepositoryImpl.java
  src/main/java/com/wanted/teamV/service/PostService.java
  src/main/java/com/wanted/teamV/service/impl/PostServiceImpl.java
  src/main/java/com/wanted/teamV/type/OrderByType.java
  src/main/java/com/wanted/teamV/type/SearchByType.java
  src/test/java/com/wanted/teamV/controller/PostControllerTest.java
  src/test/java/com/wanted/teamV/service/PostServiceImplTest.java
Labels: feature, test

#36 feat #12 - 게시물 상세 보기 API
  src/main/java/com/wanted/teamV/config/JpaAuditingConfig.java
  src/main/java/com/wanted/teamV/controller/PostController.java
  src/main/java/com/wanted/teamV/dto/res/PostDetailResDto.java
  src/main/java/com/wanted/teamV/entity/Post.java
  src/main/java/com/wanted/teamV/exception/ErrorCode.java
  src/main/java/com/wanted/teamV/repository/PostHashtagRepository.java
  src/main/java/com/wanted/teamV/service/PostService.java
  src/main/java/com/wanted/teamV/service/impl/PostServiceImpl.java
  src/test/java/com/wanted/teamV/controller/PostControllerTest.java
  src/test/java/com/wanted/teamV/service/impl/PostServiceImplTest.java
Labels: feature, test

#41 test #10 - 테스트에 H2를 사용하기 위한 alias 추가
  src/test/java/com/wanted/teamV/common/H2CustomAlias.java
  src/test/java/com/wanted/teamV/controller/StatisticsControllerTest.java
Labels: test
